import Head from "next/head";

import HeaderMain from "./components/header";
import HeroSectionMain from "./components/hero";
import SkillsSection from "./components/skills";
import ExperienceSection from "./components/experience";
import ProjectsSection from "./components/projects";
import ContactSection from "./components/contact";
import Footer from "./components/footer";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>
          Floyd Manuel Dsouza | Frontend Web Developer & UI/UX Designer
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <Link rel="icon" href="/favicon.ico" />
        <Link
          href="https://fonts.googleapis.com/css2?family=Jost:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <HeaderMain />
      <HeroSectionMain />
      <SkillsSection />
      <ExperienceSection />
      <ProjectsSection />
      <ContactSection />
      <Footer />
    </>
  );
}
